# IMT342 Robótica
## Semana 8 - Sesión 2
### Jacobiano Geométrico y Singularidades

# Ejercicio 1: Construcción Diagnóstica Independiente

## Consigna

Considere un brazo planar 2R con:

$$
a_1 = a_2 = 1
$$

evaluado en la configuración:

$$
q_1 = 0,
\qquad
q_2 = \frac{\pi}{2}
$$

Los ejes y orígenes expresados en el marco base $\{0\}$ son:

$$
o_0 =
\begin{bmatrix}
0\\
0\\
0
\end{bmatrix},
\qquad
o_1 =
\begin{bmatrix}
1\\
0\\
0
\end{bmatrix},
\qquad
o_2 =
\begin{bmatrix}
1\\
1\\
0
\end{bmatrix}
$$

y:

$$
z_0 = z_1 =
\begin{bmatrix}
0\\
0\\
1
\end{bmatrix}
$$

Complete analíticamente los vectores de radio, los productos cruz y ensamble la matriz Jacobiana.

### Junta 1

Calcular:

$$
r_1 = o_2-o_0
$$

$$
z_0 \times r_1
$$

y la columna $J_1$.

### Junta 2

Calcular:

$$
r_2 = o_2-o_1
$$

$$
z_1 \times r_2
$$

y la columna $J_2$.

Finalmente, ensamble la matriz Jacobiana:

$$
J \in \mathbb{R}^{6\times2}
$$

## Resolución

### Datos

Los orígenes son:

$$
o_0 =
\begin{bmatrix}
0\\
0\\
0
\end{bmatrix},
\qquad
o_1 =
\begin{bmatrix}
1\\
0\\
0
\end{bmatrix},
\qquad
o_2 =
\begin{bmatrix}
1\\
1\\
0
\end{bmatrix}
$$

Los ejes de las juntas son:

$$
z_0 = z_1 =
\begin{bmatrix}
0\\
0\\
1
\end{bmatrix}
$$

Para una junta rotacional, la columna del Jacobiano geométrico se construye como:

$$
J_i =
\begin{bmatrix}
z_{i-1}\times(o_2-o_{i-1})\\
z_{i-1}
\end{bmatrix}
$$

### Junta 1

Primero calculamos el vector de radio:

$$
r_1 = o_2-o_0
$$

Sustituyendo:

$$
r_1 =
\begin{bmatrix}
1\\
1\\
0
\end{bmatrix}
-
\begin{bmatrix}
0\\
0\\
0
\end{bmatrix}
$$

Por lo tanto:

$$
\boxed{
r_1 =
\begin{bmatrix}
1\\
1\\
0
\end{bmatrix}
}
$$

Ahora calculamos el producto cruz:

$$
z_0\times r_1 =
\begin{bmatrix}
0\\
0\\
1
\end{bmatrix}
\times
\begin{bmatrix}
1\\
1\\
0
\end{bmatrix}
$$

Aplicando la definición del producto cruz:

$$
z_0\times r_1 =
\begin{bmatrix}
0(0)-1(1)\\
1(1)-0(0)\\
0(1)-0(1)
\end{bmatrix}
$$

Entonces:

$$
\boxed{
z_0\times r_1 =
\begin{bmatrix}
-1\\
1\\
0
\end{bmatrix}
}
$$

La primera columna del Jacobiano es:

$$
J_1 =
\begin{bmatrix}
z_0\times r_1\\
z_0
\end{bmatrix}
$$

Por lo tanto:

$$
\boxed{
J_1 =
\begin{bmatrix}
-1\\
1\\
0\\
0\\
0\\
1
\end{bmatrix}
}
$$

### Junta 2

Calculamos el vector de radio:

$$
r_2 = o_2-o_1
$$

Sustituyendo:

$$
r_2 =
\begin{bmatrix}
1\\
1\\
0
\end{bmatrix}
-
\begin{bmatrix}
1\\
0\\
0
\end{bmatrix}
$$

Por lo tanto:

$$
\boxed{
r_2 =
\begin{bmatrix}
0\\
1\\
0
\end{bmatrix}
}
$$

Ahora calculamos:

$$
z_1\times r_2 =
\begin{bmatrix}
0\\
0\\
1
\end{bmatrix}
\times
\begin{bmatrix}
0\\
1\\
0
\end{bmatrix}
$$

Aplicando la definición del producto cruz:

$$
z_1\times r_2 =
\begin{bmatrix}
0(0)-1(1)\\
1(0)-0(0)\\
0(1)-0(0)
\end{bmatrix}
$$

Entonces:

$$
\boxed{
z_1\times r_2 =
\begin{bmatrix}
-1\\
0\\
0
\end{bmatrix}
}
$$

La segunda columna del Jacobiano es:

$$
J_2 =
\begin{bmatrix}
z_1\times r_2\\
z_1
\end{bmatrix}
$$

Por lo tanto:

$$
\boxed{
J_2 =
\begin{bmatrix}
-1\\
0\\
0\\
0\\
0\\
1
\end{bmatrix}
}
$$

### Ensamble de la matriz Jacobiana

El Jacobiano se obtiene colocando las dos columnas:

$$
J =
\begin{bmatrix}
J_1 & J_2
\end{bmatrix}
$$

Entonces:

$$
\boxed{
J =
\begin{bmatrix}
-1 & -1\\
1 & 0\\
0 & 0\\
0 & 0\\
0 & 0\\
1 & 1
\end{bmatrix}
}
$$

Por lo tanto:

$$
J\in\mathbb{R}^{6\times2}
$$

Las tres primeras filas corresponden a la componente lineal y las tres últimas a la componente angular.

In [1]:
import numpy as np

# Orígenes
o0 = np.array([0.0, 0.0, 0.0])
o1 = np.array([1.0, 0.0, 0.0])
o2 = np.array([1.0, 1.0, 0.0])

# Ejes de las juntas
z0 = np.array([0.0, 0.0, 1.0])
z1 = np.array([0.0, 0.0, 1.0])

# Vectores de radio
r1 = o2 - o0
r2 = o2 - o1

# Productos cruz
Jv1 = np.cross(z0, r1)
Jv2 = np.cross(z1, r2)

# Columnas del Jacobiano
J1 = np.concatenate((Jv1, z0))
J2 = np.concatenate((Jv2, z1))

# Ensamble
J = np.column_stack((J1, J2))

print("r1 =", r1)
print("z0 x r1 =", Jv1)
print()
print("r2 =", r2)
print("z1 x r2 =", Jv2)
print()
print("J1 =")
print(J1)
print()
print("J2 =")
print(J2)
print()
print("Jacobiano J =")
print(J)
print()
print("Dimensiones:", J.shape)

r1 = [1. 1. 0.]
z0 x r1 = [-1.  1.  0.]

r2 = [0. 1. 0.]
z1 x r2 = [-1.  0.  0.]

J1 =
[-1.  1.  0.  0.  0.  1.]

J2 =
[-1.  0.  0.  0.  0.  1.]

Jacobiano J =
[[-1. -1.]
 [ 1.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 1.  1.]]

Dimensiones: (6, 2)


### Resultado

El resultado analítico y la comprobación computacional coinciden:

$$
J =
\begin{bmatrix}
-1 & -1\\
1 & 0\\
0 & 0\\
0 & 0\\
0 & 0\\
1 & 1
\end{bmatrix}
$$

La matriz tiene dimensiones:

$$
6\times2
$$

# Ejercicio 2: Interpretación de Columnas

## Consigna

Para el Jacobiano construido en el Ejercicio 1, explique por qué ambas columnas comparten el mismo componente angular $+z$ pero exhiben componentes lineales distintos.

## Resolución

El Jacobiano obtenido en el ejercicio anterior es:

$$
J =
\begin{bmatrix}
-1 & -1\\
1 & 0\\
0 & 0\\
0 & 0\\
0 & 0\\
1 & 1
\end{bmatrix}
$$

Sus columnas son:

$$
J_1 =
\begin{bmatrix}
-1\\
1\\
0\\
0\\
0\\
1
\end{bmatrix},
\qquad
J_2 =
\begin{bmatrix}
-1\\
0\\
0\\
0\\
0\\
1
\end{bmatrix}
$$

La parte lineal corresponde a las tres primeras componentes:

$$
J_{v1} =
\begin{bmatrix}
-1\\
1\\
0
\end{bmatrix},
\qquad
J_{v2} =
\begin{bmatrix}
-1\\
0\\
0
\end{bmatrix}
$$

Estas componentes son diferentes porque cada junta se encuentra en una posición diferente respecto al efector final. Por eso los vectores de radio $r_1$ y $r_2$ son diferentes y, en consecuencia, también lo son sus productos cruz con los ejes de las juntas.

En cambio, ambas juntas son rotacionales y sus ejes de rotación son:

$$
z_0=z_1=
\begin{bmatrix}
0\\
0\\
1
\end{bmatrix}
$$

Por esta razón, ambas columnas tienen el mismo componente angular:

$$
J_{\omega1}=J_{\omega2}=
\begin{bmatrix}
0\\
0\\
1
\end{bmatrix}
$$

Por lo tanto, las componentes lineales son distintas debido a las diferentes posiciones de las juntas respecto al efector, mientras que las componentes angulares son iguales porque ambas juntas giran alrededor del mismo eje $+z$.

# Ejercicio 3: Mapeo de Velocidad Diferencial

## Consigna

Utilizando la matriz $J$ obtenida, si las velocidades de las juntas son:

$$
\dot{q} =
\begin{bmatrix}
2\\
0
\end{bmatrix}
$$

encuentre el vector de velocidad espacial en el efector final $v_e$.

Interprete física y direccionalmente las partes traslacional y angular de su respuesta.

## Resolución

La relación entre la velocidad articular y la velocidad espacial del efector es:

$$
v_e = J\dot{q}
$$

Tenemos:

$$
J =
\begin{bmatrix}
-1 & -1\\
1 & 0\\
0 & 0\\
0 & 0\\
0 & 0\\
1 & 1
\end{bmatrix}
$$

y:

$$
\dot{q} =
\begin{bmatrix}
2\\
0
\end{bmatrix}
$$

Entonces:

$$
v_e =
\begin{bmatrix}
-1 & -1\\
1 & 0\\
0 & 0\\
0 & 0\\
0 & 0\\
1 & 1
\end{bmatrix}
\begin{bmatrix}
2\\
0
\end{bmatrix}
$$

Realizando la multiplicación:

$$
v_e =
\begin{bmatrix}
(-1)(2)+(-1)(0)\\
(1)(2)+(0)(0)\\
0(2)+0(0)\\
0(2)+0(0)\\
0(2)+0(0)\\
1(2)+1(0)
\end{bmatrix}
$$

Por lo tanto:

$$
\boxed{
v_e =
\begin{bmatrix}
-2\\
2\\
0\\
0\\
0\\
2
\end{bmatrix}
}
$$

La velocidad espacial puede separarse como:

$$
v_e =
\begin{bmatrix}
v\\
\omega
\end{bmatrix}
$$

donde:

$$
v =
\begin{bmatrix}
-2\\
2\\
0
\end{bmatrix}
$$

es la velocidad lineal del efector y:

$$
\omega =
\begin{bmatrix}
0\\
0\\
2
\end{bmatrix}
$$

es su velocidad angular.

### Interpretación física

La componente lineal:

$$
v =
\begin{bmatrix}
-2\\
2\\
0
\end{bmatrix}
$$

indica que el efector se mueve instantáneamente en el plano $xy$, con velocidad $-2$ en la dirección $x$ y velocidad $2$ en la dirección $y$.

La componente angular:

$$
\omega =
\begin{bmatrix}
0\\
0\\
2
\end{bmatrix}
$$

indica que el efector presenta una velocidad angular de magnitud $2$ alrededor del eje $+z$.

Como $\dot q_2=0$, todo el movimiento instantáneo es producido por la primera junta.

In [2]:
import numpy as np

J = np.array([
    [-1, -1],
    [ 1,  0],
    [ 0,  0],
    [ 0,  0],
    [ 0,  0],
    [ 1,  1]
], dtype=float)

q_dot = np.array([2, 0], dtype=float)

v_e = J @ q_dot

print("Velocidad espacial del efector:")
print(v_e)

print()
print("Velocidad lineal:")
print(v_e[:3])

print()
print("Velocidad angular:")
print(v_e[3:])

Velocidad espacial del efector:
[-2.  2.  0.  0.  0.  2.]

Velocidad lineal:
[-2.  2.  0.]

Velocidad angular:
[0. 0. 2.]


### Resultado

La velocidad espacial obtenida es:

$$
\boxed{
v_e =
\begin{bmatrix}
-2\\
2\\
0\\
0\\
0\\
2
\end{bmatrix}
}
$$

La parte traslacional es:

$$
\boxed{
v =
\begin{bmatrix}
-2\\
2\\
0
\end{bmatrix}
}
$$

y la parte angular es:

$$
\boxed{
\omega =
\begin{bmatrix}
0\\
0\\
2
\end{bmatrix}
}
$$

# Ejercicio 4: Cinemática Inversa Diferencial

## Consigna

Sabiendo que el sub-Jacobiano planar de traslación evaluado es:

$$
J_p =
\begin{bmatrix}
-1 & -1\\
1 & 0
\end{bmatrix}
$$

y dado un comando de velocidad deseada en el efector:

$$
\dot{p}_d =
\begin{bmatrix}
1\\
0
\end{bmatrix}
$$

calcule analíticamente las velocidades articulares requeridas $\dot{q}$.

Verifique multiplicando su respuesta por $J_p$.

## Resolución

La relación diferencial es:

$$
\dot{p}_d = J_p\dot{q}
$$

Tenemos:

$$
\begin{bmatrix}
1\\
0
\end{bmatrix}
=
\begin{bmatrix}
-1 & -1\\
1 & 0
\end{bmatrix}
\begin{bmatrix}
\dot q_1\\
\dot q_2
\end{bmatrix}
$$

Esto produce el sistema:

$$
-\dot q_1-\dot q_2=1
$$

$$
\dot q_1=0
$$

De la segunda ecuación:

$$
\boxed{\dot q_1=0}
$$

Sustituyendo en la primera:

$$
-(0)-\dot q_2=1
$$

por lo que:

$$
\boxed{\dot q_2=-1}
$$

Entonces:

$$
\boxed{
\dot q =
\begin{bmatrix}
0\\
-1
\end{bmatrix}
}
$$

### Verificación

Multiplicamos nuevamente:

$$
J_p\dot q =
\begin{bmatrix}
-1 & -1\\
1 & 0
\end{bmatrix}
\begin{bmatrix}
0\\
-1
\end{bmatrix}
$$

$$
=
\begin{bmatrix}
(-1)(0)+(-1)(-1)\\
(1)(0)+(0)(-1)
\end{bmatrix}
$$

$$
=
\begin{bmatrix}
1\\
0
\end{bmatrix}
$$

que coincide con la velocidad deseada.

In [4]:
import numpy as np

Jp = np.array([
    [-1, -1],
    [ 1,  0]
], dtype=float)

p_dot_d = np.array([1, 0], dtype=float)

q_dot = np.linalg.solve(Jp, p_dot_d)

print("Velocidades articulares:")
print(q_dot)

print()
print("Verificación:")
print(Jp @ q_dot)

Velocidades articulares:
[-0. -1.]

Verificación:
[1. 0.]


# Ejercicio 5: Clasificación de Rango

## Consigna

Dadas las siguientes matrices Jacobianas hipotéticas:

$$
J_A =
\begin{bmatrix}
1 & 0\\
0 & 1
\end{bmatrix}
$$

y:

$$
J_B =
\begin{bmatrix}
1 & 2\\
2 & 4
\end{bmatrix}
$$

Calcule el rango de cada una.

Físicamente, ¿qué implica el rango de $J_B$ para la movilidad de ese manipulador?

## Resolución

### Matriz $J_A$

Tenemos:

$$
J_A =
\begin{bmatrix}
1 & 0\\
0 & 1
\end{bmatrix}
$$

Su determinante es:

$$
\det(J_A)=(1)(1)-(0)(0)=1
$$

Como el determinante es diferente de cero, las dos columnas son linealmente independientes.

Por lo tanto:

$$
\boxed{\operatorname{rango}(J_A)=2}
$$

---

### Matriz $J_B$

Tenemos:

$$
J_B =
\begin{bmatrix}
1 & 2\\
2 & 4
\end{bmatrix}
$$

Observamos que la segunda columna es el doble de la primera:

$$
\begin{bmatrix}
2\\
4
\end{bmatrix}
=
2
\begin{bmatrix}
1\\
2
\end{bmatrix}
$$

Por lo tanto, las columnas son linealmente dependientes.

El determinante también permite comprobarlo:

$$
\det(J_B)=(1)(4)-(2)(2)=4-4=0
$$

Por lo tanto:

$$
\boxed{\operatorname{rango}(J_B)=1}
$$

### Interpretación física

Un rango igual a $1$ significa que el Jacobiano solo puede generar una dirección independiente de movimiento en el espacio de tareas representado por esta matriz.

Por lo tanto, el manipulador no puede producir independientemente las dos direcciones de movimiento representadas por las dos filas. Existe una pérdida de movilidad instantánea.

In [5]:
import numpy as np

JA = np.array([
    [1, 0],
    [0, 1]
], dtype=float)

JB = np.array([
    [1, 2],
    [2, 4]
], dtype=float)

print("Rango de JA:", np.linalg.matrix_rank(JA))
print("Rango de JB:", np.linalg.matrix_rank(JB))

print()
print("det(JA) =", np.linalg.det(JA))
print("det(JB) =", np.linalg.det(JB))

Rango de JA: 2
Rango de JB: 1

det(JA) = 1.0
det(JB) = 0.0


# Ejercicio 6: Calificación del Determinante

## Consigna

Un compañero afirma:

> "Un robot se encuentra en singularidad exacta si y solo si $\det(J)=0$".

Explique por qué esta afirmación no es universalmente cierta, especialmente para un Jacobiano $6\times7$.

## Resolución

La afirmación no es universalmente cierta porque el determinante solamente está definido para matrices cuadradas.

Un Jacobiano de tamaño:

$$
6\times7
$$

no es cuadrado, por lo que:

$$
\boxed{\det(J)\text{ no está definido}}
$$

Por lo tanto, no podemos utilizar directamente el determinante del Jacobiano completo para determinar si existe una singularidad.

En un robot con un Jacobiano rectangular, la condición relevante es analizar el **rango** del Jacobiano.

Para un Jacobiano:

$$
J\in\mathbb{R}^{6\times7}
$$

el rango máximo posible es:

$$
\operatorname{rango}(J)=6
$$

Si el rango disminuye por debajo de ese valor máximo, se pierde una o más direcciones independientes de velocidad en el espacio de tareas.

Por lo tanto, para un Jacobiano rectangular, el análisis de singularidad se realiza mediante el rango, la dependencia lineal de sus columnas o herramientas equivalentes, y no mediante $\det(J)$ del Jacobiano completo.

El determinante puede utilizarse cuando se trabaja con un sub-Jacobiano cuadrado. Por ejemplo, en el Ejercicio 4:

$$
J_p=
\begin{bmatrix}
-1 & -1\\
1 & 0
\end{bmatrix}
$$

es una matriz $2\times2$, por lo que su determinante sí está definido.

# Ejercicio 7: Singularidad Geométrica 2R

## Consigna

Para el manipulador 2R, compare la configuración de codo a $90^\circ$:

$$
q_2=\frac{\pi}{2}
$$

con el brazo completamente extendido:

$$
q_2=0
$$

Identifique explícitamente cuál es la configuración singular, describa la relación entre las columnas de $J_p$ en ese punto y nombre la dirección de movimiento cartesiano local que se pierde físicamente.

## Resolución

### Configuración con $q_2=\frac{\pi}{2}$

Para esta configuración, el sub-Jacobiano planar dado anteriormente es:

$$
J_p=
\begin{bmatrix}
-1 & -1\\
1 & 0
\end{bmatrix}
$$

Calculamos su determinante:

$$
\det(J_p)
=
(-1)(0)-(-1)(1)
$$

$$
\det(J_p)=1
$$

Como:

$$
\det(J_p)\neq0
$$

las dos columnas son linealmente independientes y el rango es:

$$
\boxed{\operatorname{rango}(J_p)=2}
$$

Por lo tanto, esta configuración no es singular.

---

### Configuración con $q_2=0$

Cuando el brazo está completamente extendido, ambos eslabones quedan alineados.

Para un robot 2R planar, el sub-Jacobiano de traslación tiene la forma:

$$
J_p=
\begin{bmatrix}
-a_1\sin(q_1)-a_2\sin(q_1+q_2)
&
-a_2\sin(q_1+q_2)
\\
a_1\cos(q_1)+a_2\cos(q_1+q_2)
&
a_2\cos(q_1+q_2)
\end{bmatrix}
$$

Con:

$$
q_2=0
$$

las dos columnas quedan alineadas.

Para la configuración utilizada anteriormente, con $q_1=0$ y $a_1=a_2=1$:

$$
J_p=
\begin{bmatrix}
0 & 0\\
2 & 1
\end{bmatrix}
$$

Las columnas son:

$$
J_{p1}=
\begin{bmatrix}
0\\
2
\end{bmatrix},
\qquad
J_{p2}=
\begin{bmatrix}
0\\
1
\end{bmatrix}
$$

y se observa que:

$$
J_{p1}=2J_{p2}
$$

Por lo tanto, las columnas son linealmente dependientes.

El determinante es:

$$
\det(J_p)=(0)(1)-(0)(2)=0
$$

y:

$$
\boxed{\operatorname{rango}(J_p)=1}
$$

Por lo tanto:

$$
\boxed{q_2=0\text{ es una configuración singular}}
$$

### Dirección de movimiento perdida

En esta configuración, el brazo está completamente extendido y el movimiento instantáneo generado por las articulaciones solamente puede producirse en una dirección perpendicular al brazo.

La dirección radial, es decir, la dirección a lo largo del brazo, no puede producirse instantáneamente mediante pequeñas velocidades articulares.

Por lo tanto, se pierde una dirección independiente de movimiento cartesiano.

In [6]:
import numpy as np

# Configuración no singular: q2 = pi/2
Jp_regular = np.array([
    [-1, -1],
    [ 1,  0]
], dtype=float)

# Configuración singular: q1 = 0, q2 = 0, a1 = a2 = 1
Jp_singular = np.array([
    [0, 0],
    [2, 1]
], dtype=float)

print("Configuración q2 = pi/2")
print(Jp_regular)
print("Rango =", np.linalg.matrix_rank(Jp_regular))
print("Determinante =", np.linalg.det(Jp_regular))

print()
print("Configuración q2 = 0")
print(Jp_singular)
print("Rango =", np.linalg.matrix_rank(Jp_singular))
print("Determinante =", np.linalg.det(Jp_singular))

Configuración q2 = pi/2
[[-1. -1.]
 [ 1.  0.]]
Rango = 2
Determinante = 1.0

Configuración q2 = 0
[[0. 0.]
 [2. 1.]]
Rango = 1
Determinante = 0.0


# Ejercicio 8: Amplificación Cercana a la Singularidad

## Consigna

Use el Jacobiano diagonal simplificado:

$$
J_\epsilon =
\begin{bmatrix}
1 & 0\\
0 & \epsilon
\end{bmatrix}
$$

Si se demanda la velocidad cartesiana constante:

$$
\dot{x}_d =
\begin{bmatrix}
0\\
1
\end{bmatrix}
$$

calcule la velocidad articular requerida $\dot q_2$ para:

$$
\epsilon=1,\quad 0.1,\quad 0.01
$$

Explique por qué estar "no exactamente en singularidad" no significa que la inversión sea segura.

## Resolución

Partimos de la relación:

$$
\dot{x}_d=J_\epsilon\dot q
$$

Tenemos:

$$
\begin{bmatrix}
0\\
1
\end{bmatrix}
=
\begin{bmatrix}
1 & 0\\
0 & \epsilon
\end{bmatrix}
\begin{bmatrix}
\dot q_1\\
\dot q_2
\end{bmatrix}
$$

Realizando la multiplicación:

$$
\begin{bmatrix}
0\\
1
\end{bmatrix}
=
\begin{bmatrix}
\dot q_1\\
\epsilon\dot q_2
\end{bmatrix}
$$

Por igualdad de componentes:

$$
\dot q_1=0
$$

y:

$$
\epsilon\dot q_2=1
$$

Por lo tanto:

$$
\boxed{
\dot q_2=\frac{1}{\epsilon}
}
$$

### Caso 1: $\epsilon=1$

$$
\dot q_2=\frac{1}{1}=1
$$

Por lo tanto:

$$
\boxed{\dot q_2=1}
$$

### Caso 2: $\epsilon=0.1$

$$
\dot q_2=\frac{1}{0.1}=10
$$

Por lo tanto:

$$
\boxed{\dot q_2=10}
$$

### Caso 3: $\epsilon=0.01$

$$
\dot q_2=\frac{1}{0.01}=100
$$

Por lo tanto:

$$
\boxed{\dot q_2=100}
$$

### Interpretación

Aunque para $\epsilon>0$ el Jacobiano todavía es invertible, cuando $\epsilon$ se aproxima a cero la velocidad articular requerida crece rápidamente:

$$
1\rightarrow10\rightarrow100
$$

En el límite:

$$
\epsilon\rightarrow0
$$

se tiene:

$$
\dot q_2=\frac{1}{\epsilon}\rightarrow\infty
$$

Por lo tanto, estar cerca de una singularidad puede producir una gran amplificación de la velocidad articular necesaria para conseguir una velocidad cartesiana determinada.

Esto muestra que no es necesario estar exactamente en la singularidad para que la inversión del Jacobiano sea problemática.

In [7]:
import numpy as np

epsilons = [1, 0.1, 0.01]

x_dot_d = np.array([0.0, 1.0])

for epsilon in epsilons:
    J_epsilon = np.array([
        [1.0, 0.0],
        [0.0, epsilon]
    ])

    q_dot = np.linalg.solve(J_epsilon, x_dot_d)

    print(f"epsilon = {epsilon}")
    print("J_epsilon =")
    print(J_epsilon)
    print("q_dot =", q_dot)
    print("q_dot2 =", q_dot[1])
    print()

epsilon = 1
J_epsilon =
[[1. 0.]
 [0. 1.]]
q_dot = [0. 1.]
q_dot2 = 1.0

epsilon = 0.1
J_epsilon =
[[1.  0. ]
 [0.  0.1]]
q_dot = [ 0. 10.]
q_dot2 = 10.0

epsilon = 0.01
J_epsilon =
[[1.   0.  ]
 [0.   0.01]]
q_dot = [  0. 100.]
q_dot2 = 100.0



### Resultado

Los resultados obtenidos son:

| $\epsilon$ | $\dot q_2$ |
|---:|---:|
| $1$ | $1$ |
| $0.1$ | $10$ |
| $0.01$ | $100$ |

Por lo tanto:

$$
\boxed{
\epsilon=1 \Rightarrow \dot q_2=1
}
$$

$$
\boxed{
\epsilon=0.1 \Rightarrow \dot q_2=10
}
$$

$$
\boxed{
\epsilon=0.01 \Rightarrow \dot q_2=100
}
$$

A medida que $\epsilon$ se aproxima a cero, la velocidad articular requerida aumenta considerablemente. Por ello, una configuración que todavía no es exactamente singular puede presentar una inversión del Jacobiano numéricamente sensible y exigir velocidades articulares muy grandes.